version: 2.10
orbs: 
  snyk: snyk/snyk@1.1.2
env:
  SNYK_TOKEN: ${{ secrets.SYNK_TOKEN }}
jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
      
    steps:
      - checkout
      - run: node --version
      - run: npm install
      - run: npm test
      - snyk/scan:
          fail-on-issues: true
