version: 2.10
orbs: 
  snyk: snyk/snyk@1.1.2
env:
  SNYK_TOKEN: 3551382d-4809-44fa-ac27-86fea9e25657
jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
      
    steps:
      - checkout
      - run: node --version
      - run: npm install
      - run: npm test
      - snyk/scan:
          fail-on-issues: true
